### ISSUE TITLE
cvmfs: When one mount is OOM killed, all the other mounts are killed by supervisor

### ISSUE THREAD

**Issue by krishnan-r** [sciencebox/charts#115]
We observed that when one mountpoint is killed (possibly by OOM), supervisor exits after killing all the other mountpoints. 

Expected Behaviour: The processes that died could be restarted, without the whole container restarting, leaving other mountpoints intact

Screenshot of logs:

![image](https://user-images.githubusercontent.com/6822941/207114183-50a68ad2-885c-4f82-a904-4a96673c35bb.png)

cc @etejedor

**Comment by ebocchi** [comment]
Yes, this is due to the fact the mountpoint becomes stale, cvmfs2 is unable to re-mount, supervisord tries to revive it (but continues to fail due to stale mount), and eventually commits suicide...

**Comment by ebocchi** [comment]
Let me see if https://github.com/sciencebox/charts/issues/35 can help here
