### ISSUE TITLE
eos-instance-config: Add users known to ocis-idp

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#25]
The eos-instance-config chart should have the ability to create home directories for the users know to the idp:
- marie
- einstein
- reva
- ...
Review how user creation is implemented to consider also this users.

**Comment by SamuAlfageme** [comment]
@ebocchi agreed for pre-creating the `/eos/user` bit as the existing `eos` image only comes with `/dockertest`.

However, reva provisions the home directories of the users upon their first login (or if they don't exist). So logging in with `einstein` creates the entire `/eos/user/e/einstein` file tree. Does SWAN works in a similar way? cc/ @diocas

**Comment by ebocchi** [comment]
We are in a split brain :
- eos has /eos/user/u/user7 but idp does not
- idp has einstein but there is no /eos/user/e/einstein

**Comment by ebocchi** [comment]
Done with:
- https://github.com/sciencebox/charts/commit/995d89ba60cb079cbffad18317f015635e5eda4f
- https://github.com/sciencebox/charts/commit/21d715f2c66cdabcdeac9e7024fbc74e3c0320c5
