### ISSUE TITLE
cvmfs: Clean mountpoints before mouting

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#35]
To be on the safe side, it is better to `umount` the CVMFS mountpoints before starting the cvmfs client processes.
```
kl -f -n swan swan-cvmfs-9b7p7 cvmfs-init1-create-mountpoints
mkdir: cannot create directory '/cvmfs/cms.cern.ch': File exists
chown: cannot access '/cvmfs/cms.cern.ch': Transport endpoint is not connected
mkdir: cannot create directory '/cvmfs/compass.cern.ch': File exists
chown: cannot access '/cvmfs/compass.cern.ch': Transport endpoint is not connected
```

`umount /cvmfs/<the_stuck_ones>` fixes the problem.

Maybe an init container that does umount before mounting?

**Comment by krishnan-r** [comment]
cc @etejedor

**Comment by ebocchi** [comment]
Actually, this may not work if there are external processes keeping file handles open on the stale mount.
This case is hardly fixable, though: The process should be killed to release to handle (and then unmount + remount)

**Comment by etejedor** [comment]
So if there's some process with an open file in the stale mount, you can't (force) unmount?

**Comment by ebocchi** [comment]
> So if there's some process with an open file in the stale mount, you can't (force) unmount?

You can force unmount but will likely not work.
You can also lazy unmount but it is not fixing the problem either as it just hides the file system from the mount hierarchy and actually unmount onky when the reference counter for that fs goes to 0 (which won't happen unless you unstuck the process keeping the file open).

We can test this, but CVMFS is typically quite easy here since it is read-only. It may just work upon remount
