### ISSUE TITLE
revad: Switch to upstream reva container image

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#37]
Replace custom container image with additional logging with upstream `cs3org/revad` image.
Make sure the latter is properly tagged and we can pin to a specific version. If now, make a copy to sciencebox registry.

**Comment by jimil749** [comment]
- So the storage-providers that need to talk to eos, require the `revad-eos` image which is tagged [here](https://hub.docker.com/layers/revad/cs3org/revad/latest-eos/images/sha256-7ed1307b1394f5b192af0848c9ed6c9643a109e20465f6c61a40b07f6d4713fa?context=explore). Tested with the upstream image - works fine. 

- And the gateway can simple use `cs3org/revad` image.

**Comment by SamuAlfageme** [comment]
@jimil749 absolutely, this is perfectly fine for the time being. We'll reduce the size of the `revad-eos` image in a follow-up PR on [cs3org/reva](github.com/cs3org/reva)
