### ISSUE TITLE
revad: Use MariaDB to store sharing information

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#45]

**Comment by jimil749** [comment]
We can use the upstream charts here - https://artifacthub.io/packages/helm/bitnami/mariadb

**Comment by ebocchi** [comment]
Absolutely! You just won the issue :)

**Comment by jimil749** [comment]
Also herein: we have pre-configure mariadb to have appropriate db schema: https://new.cernbox.cern.ch/s/nZGWdZVVQPleBZI - `oc_share` and `oc_share_status` are relevant

**Comment by jimil749** [comment]
Closing this because sharing is working fine
