### ISSUE TITLE
make frontier-squid cache persistent using PVC storage?

### ISSUE THREAD

**Issue by rptaylor** [sciencebox/charts#55]
@ebocchi what would you think about using PVC storage and a statefulSet instead of deployment for frontier-squid?
This would allow the chart to scale in a more robust way. I could probably contribute to a MR.

Currently as a deployment it can scale to > 1 pod but the pods only use ephemeral storage, so each pod restart/upgrade/eviction causes the cache to be lost, which would reduce performance. Actually it looks like the pods don't even use an emptyDir, they write into the location of the container image which I think may incur a performance hit due to overlayfs layers.

We would probably also want a separate option to control whether an emptydir or PVC is used, the default behaviour (use ephemeral storage) could remain the same.

**Comment by rptaylor** [comment]
@ebocchi very astute point; I also recall that restarting frontier-squid used to clear the cache but I thought it had been improved. I'll get confirmation.

**Comment by rptaylor** [comment]
Dave confirmed that frontier-squid (unlike normal squid)  empties the cache by default when restarting, because apparently squid sometimes corrupts files after a restart (!!!)

There is a way to change that but it is apparently not recommended and interferes with log compression:
https://twiki.cern.ch/twiki/bin/view/Frontier/InstallSquid#Laptop_disconnected_network_oper

**Comment by ebocchi** [comment]
That's interesting, thanks for checking!
I wonder if using the frontier flavor is relevant here: It has some optimization to better handle the ATLAS db queries but I doubt they are relevant for typical CVMFS traffic. The choice was drive by the fact we use it in production for the site-caches and I could mostly copy-paste the configuration file.

emptyDir tracked at https://github.com/sciencebox/charts/issues/60

**Comment by rptaylor** [comment]
Yes, the automatic cache emptying is a frontier-squid 'feature' to work around a suspected bug in vanilla squid, where data got corrupted after a restart. Dave said the corruption could not be reproduced easily so the developers could not investigate it.
Though it may not be applicable for CVMFS, we do also need squid for Frontier DB caching for ATLAS compute jobs, so we have to use frontier-squid with its patch to support Last-Modified and If-Modified-Since headers.

**Comment by rptaylor** [comment]
I have always been interested in other (more modern) forward caching proxies, there must be other alternatives that support Last-Modified and If-Modified-Since headers, e.g. Envoy, but it would be a lot of work to commission a completely new one.
