### ISSUE TITLE
frontier-squid: Use emptyDir for cache directory

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#60]
As per https://github.com/sciencebox/charts/issues/55
PVCs not needed as frontier-squid empties the cache upon restart.

**Comment by rptaylor** [comment]
I would have sworn there was no volume, but I must have been looking in the wrong place or mis-searched.
The emptydir is already there: https://github.com/sciencebox/charts/blob/master/frontier-squid/templates/deployment.yaml#L89

**Comment by ebocchi** [comment]
0-effort fix :)
