### ISSUE TITLE
frontier-squid pod should run as (unprivileged) squid user

### ISSUE THREAD

**Issue by rptaylor** [sciencebox/charts#61]
The squid deployment does not have a securityContext definition so the behaviour is not fully defined.
If a cluster has PSP enabled, the pod fails to run:
```
       message: 'container has runAsNonRoot and image will run as root (pod: "frontier-squid-5cb58b887c-6dh44_frontier-squid(2e034c08-1a38-4514-9652-0719199bf6d8)",
```
indicating that, lacking any securityContext definition, the default of the Docker image is to run as root, while a PSP enforces runAsNonRoot.

Presumably it is currently working on clusters without PSP by running as root, however the image contains a 'squid' user which should be used; this would improve security by running unprivileged and also support running on clusters with PSP (or if the new Pod Security Standards are enabled I think it would be a similar variation of this problem).

**Comment by rptaylor** [comment]
With an update to the container image:
https://gitlab.cern.ch/sciencebox/docker-images/frontier-squid/-/merge_requests/1
I propose to solve this by adding a securityContext to the deployment:
```
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
        fsGroup: 5000
```
@ebocchi

**Comment by ebocchi** [comment]
Thanks @rptaylor -- https://github.com/sciencebox/charts/pull/62 is merged now
