### ISSUE TITLE
frontier-squid ACL for frontier servers

### ISSUE THREAD

**Issue by rptaylor** [sciencebox/charts#77]
To use this for Frontier access we need either 

- Frontier ACLs such as
```
# copied from frontier-squid package
acl CMS_FRONTIER dstdom_regex ^(cmsfrontier.*\.cern\.ch|cms.*frontier\.openhtc\.io)$
acl ATLAS_FRONTIER dstdom_regex ^(frontier.*\.racf\.bnl\.gov|atlas.*frontier.*\.cern\.ch|cc.*\.in2p3\.fr|lcg.*\.gridpp\.rl\.ac\.uk|(.*frontier.*|tier1nfs)\.triumf\.ca|atlas.*frontier\.openhtc\.io)$
```
which exacerbates the issue of needing to track/copy updates from upstream frontier-squid, though they may be rare, or
-  a source-based ACL to allow local clients on the cluster to access any destination. The default source could be 10.233.64.0/18 which is usually (?) the subnet for all k8s pods, but this can vary among k8s distributions. It would also make practically every other ACL irrelevant.

**Comment by ebocchi** [comment]
https://github.com/sciencebox/charts/pull/78 got merged, which fixes the issue (though exacerbates tracking from upstream).

Indeed, letting the clients reaching everything through squid would fix all problems, but it sounded like a very bad idea to me.
The default range of IPs for k8s pods is vastly unknown to me: I see a mixture of 172.17.0.0, 10.233.64.0, and even 10.0.0.0 here
