### ISSUE TITLE
frontier-squid: individually addressable pods for CVMFS sharding

### ISSUE THREAD

**Issue by rptaylor** [sciencebox/charts#97]
@ebocchi 
Although a statefulset may not be useful [for cache persistence](https://github.com/sciencebox/charts/issues/55), the new CVMFS [sharding](https://cvmfs.readthedocs.io/en/latest/cpt-configure.html#sct-proxy-sharding) functionality is very attractive - especially on k8s where additional capacity is provided by scaling up more replica pods which may have smaller disk caches, and potentially get erased more frequently by restarts. Since it is trivial on k8s to scale up the deployment to N pods, it is pretty much guaranteed there will be multiple redundant pods, with a benefit to be realized if the multiple caches can be sharded by client access to increase hit rates and reduce cache duplication, instead of just using accessing all the caches in a randomly load balanced way.

This would also be at least one step towards https://github.com/sciencebox/charts/issues/66

emptydirs and a service can still be used in the same way as with a deployment currently.  I don't think there would be any downside to switching to a statefulset except maybe having to handle updates differently, with a RollingUpdate strategy? 
There might be some [restrictions](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets) on which fields can be changed though.

What is even better, it looks like the headless service for statefulset pods is actually implemented as a round-robin DNS alias, meaning that CVMFS will natively detect each of the backing pods!

```
bash-4.2$ host nginx.development.svc                 
nginx.development.svc.cluster-dev.local has address 10.233.114.188
nginx.development.svc.cluster-dev.local has address 10.233.87.172
nginx.development.svc.cluster-dev.local has address 10.233.96.166

bash-4.2$ host web-0.nginx.development
web-0.nginx.development.svc.cluster-dev.local has address 10.233.114.188
bash-4.2$ host web-1.nginx.development
web-1.nginx.development.svc.cluster-dev.local has address 10.233.96.166
bash-4.2$ host web-2.nginx.development
web-2.nginx.development.svc.cluster-dev.local has address 10.233.87.172
```

**Comment by ebocchi** [comment]
@rptaylor 
Indeed, this proxy sharding feature looks very interesting. I don't think a client implementing it has been release yet (will confirm soon).

What do you think should happen to the chart?
- Support both Deployment and StatefulSet to deploy the frontier-squid pod
- Drop Deployment immediately and keep only StatefulSet (which would not break compatibility with clients anyway)

I wanted to clean up the image tags and update the list of allowed stratum one following the release of `frontier-squid-4.7.2-1` and its update to MAJOR_CVMFS. This can go together with it in a new tag.

**Comment by rptaylor** [comment]
Maintaining two different options in the chart seems like a lot of overhead, I would suggest just switching to a StatefulSet if it works with the future sharding feature and has no other downsides.  I am not as familiar working with StatefulSets but I found that some fields were immutable which would make updates and changes difficult; however I thought that a rolling update strategy would take care of that but I did not get that working yet.  I didn't spend much time on it yet though.  Perhaps you are more familiar due to using StatefulSets for EOS.

I might be able to contribute a PR but it would have to be rather later. Don't let me stop you though if you're inclined. :)

**Comment by ebocchi** [comment]
I had a second though about this and it may be worth looking into replicasets backed with an headless service with selectors. I understand the proxy sharding feature on the cvmfs client is bases on the list of active proxies, which is compiled from the list of A records returned by the DNS.
To be tested...
I also confirmed the feature has not been packages in a stable release (there should be a 2.10 tag coming out) yet.

**Comment by rptaylor** [comment]
That is a good point, headless services with selectors are implemented via multiple DNS 'A' records, regardless of the type of pod controller actually. In fact a [headless clusterIP service](https://kubernetes.io/docs/concepts/services-networking/service/#with-selectors) works just as well with a deployment as a statefulset, so there should be no need to change from using a deployment!

The headless service works by propagating cluster DNS updates very quickly whenever a pod comes or goes.
Looking at https://sft.its.cern.ch/jira/si/jira.issueviews:issue-html/CVM-457/CVM-457.html 
by default it will only check every minute for DNS updates to proxies. However this can be changed via
[CVMFS_DNS_MIN_TTL](https://cvmfs.readthedocs.io/en/stable/apx-parameters.html)

The default DNS TTL seems to be 5 seconds:
``
$ dig  +nocmd +noall +answer +ttlunits rpt-dep-s.sandbox.svc.kirin-dev.local 
rpt-dep-s.sandbox.svc.cluster-dev.local. 5s IN A	10.233.102.10
rpt-dep-s.sandbox.svc.cluster-dev.local. 5s IN A	10.233.99.11
rpt-dep-s.sandbox.svc.cluster-dev.local. 5s IN A	10.233.88.7
```
I guess that is what nodelocaldns is for, to cache and distribute DNS load while also being rapidly responsive.

So it seems we should only need to change the service to headless and perhaps decrease CVMFS_DNS_MIN_TTL to a small value on clients, for CVMFS proxy sharding to work with the frontier-squid helm chart.

However a side-effect of this for us is that we would have to change how the CVMFS client (installed on our nodes) access the frontier-squids, currently we rely on a ClusterIP since the nodes don't have cluster DNS.

**Comment by ebocchi** [comment]
Hi @rptaylor 
I eventually managed to look into this:
- There is a new frontier-squid image with tag `4.17-2.1` that cleans the previous re-tagging of containers. It also comes with the new MAJOR_CVMFS additions for Sampa (BR) and Swinburne (AU)
- I have set `clusterIP: None` into the k8s service specs to get the headless service. It seems to be working for me, tested with 3 replicas.

```
]# helm list
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
headless	default  	1       	2022-11-22 17:09:10.012054688 +0100 CET	deployed	frontier-squid-0.1.4	4.17-2.1   

# kubectl get pods
NAME                                       READY   STATUS    RESTARTS   AGE
debugger-86f54b7fd6-247m8                  1/1     Running   0          7m3s
headless-frontier-squid-865476c6fd-kmhkw   1/1     Running   0          3m12s
headless-frontier-squid-865476c6fd-mpmpd   1/1     Running   0          3m12s
headless-frontier-squid-865476c6fd-r2t8v   1/1     Running   0          3m12s

# kubectl get svc
NAME                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
headless-frontier-squid   ClusterIP   None         <none>        3128/TCP   3m49s
kubernetes                ClusterIP   10.96.0.1    <none>        443/TCP    29d

# kubectl describe svc headless-frontier-squid
Name:              headless-frontier-squid
Namespace:         default
Labels:            app.kubernetes.io/instance=headless
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=frontier-squid
                   app.kubernetes.io/version=4.17-2.1
                   helm.sh/chart=frontier-squid-0.1.4
Annotations:       meta.helm.sh/release-name: headless
                   meta.helm.sh/release-namespace: default
Selector:          app.kubernetes.io/instance=headless,app.kubernetes.io/name=frontier-squid
Type:              ClusterIP
IP Families:       <none>
IP:                None
IPs:               None
Port:              squid  3128/TCP
TargetPort:        3128/TCP
Endpoints:         172.17.0.3:3128,172.17.0.5:3128,172.17.0.6:3128
Session Affinity:  None
Events:            <none>


# kubectl exec -it debugger-86f54b7fd6-247m8 --  bash
# nslookup headless-frontier-squid
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	headless-frontier-squid.default.svc.cluster.local
Address: 172.17.0.5
Name:	headless-frontier-squid.default.svc.cluster.local
Address: 172.17.0.6
Name:	headless-frontier-squid.default.svc.cluster.local
Address: 172.17.0.3
```

It is all tagged as frontier-squid 0.1.5.
Hope this helps!

**Comment by ebocchi** [comment]
Do you also use the CVMFS client chart and container from sciencebox?
We don't have a 2.10 there yet

**Comment by rptaylor** [comment]
No, we install CVMFS on the nodes and use a hostPath.

**Comment by rptaylor** [comment]
I can't reconfigure the node network environment to use cluster DNS yet at the moment (needed to access a headless service) because of a Kubespray bug. https://github.com/kubernetes-sigs/kubespray/pull/8575

But that is unrelated to the frontier-squid chart, looks like everything should work there.
